# Generated by Django 5.0 on 2023-12-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=255)),
                ('year', models.IntegerField(blank=True)),
                ('describe', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('url', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
