# Generated by Django 5.0 on 2024-01-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamcat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='slug',
            field=models.SlugField(default='#', max_length=255),
        ),
    ]
