# Generated by Django 5.0 on 2024-01-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamcat', '0004_alter_games_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='games',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='steamcat.tagposts'),
        ),
    ]
